- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/controller/AuthenticationController.java
- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/filter/JWTAuthenticationFilter.java
- openchpl-sql/create-database.sql
- openchpl-sql/drop-openchpl.sql
- openchpl-sql/openchpl-role-template.sql
- openchpl-sql/openchpl.sql
- openchpl-sql/preload-user_contact_acl.sql
- openchpl-sql/reset.sh
Some changes to the database to support the acl and user preloading stuff, as well as minor JSON updates in the AuthenticationController and AuthenticationFilter
> Ocd 144: Wire up authentication mechanism

- chpl/chpl-etl/src/main/resources/graphs/openchpl_etl.grf
- chpl/chpl-etl/src/main/resources/graphs/openchpl_insert_certified_product.grf
Should be importing Certification Date correctly now
> Fixed OCD-164; changed 'yyyy' to 'yy' in graphs

- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerTest.java
- chpl/chpl-service/src/test/resources/data/testData.xml
- openchpl-sql/openchpl.sql
in test data to have negative IDs (preventing conflicts with data
created in unit tests)
> Fixed timestamp / date bug in data model. Updated certification events

- chpl/chpl-service/src/main/java/gov/healthit/chpl/certifiedProduct/upload/CertifiedProductHandler2015.java
- chpl/chpl-service/src/main/webapp/WEB-INF/web.xml
> OCD-859: parse upload file details as floats and round to ints. Remove

- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/presenter/CertifiedProduct2014CsvPresenter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/presenter/CertifiedProductCsvPresenter.java
I think i should have done this in a different branch... sorry. Started in development and decided since it was a small change and the CSV task has otherwise already been QAed so hoping it's not a big deal.
> OCD-946: add columns to csv view

- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
Hand-coded this in a couple of places on AHRQ-DEV and it appeared to work. It would be a good idea to do more thorough testing on staging if the team agrees to these changes.
> OCD-924: adjust tx management to work with caching

- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/CHPLAuthenticationSecurityConfig.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/CHPLConfig.java
- chpl/chpl-service/src/main/resources/ehCache.xml
- chpl/chpl-service/src/main/webapp/WEB-INF/rest-servlet.xml
Please review and merge to dev for additional testing. Also, please note that we need to add this argument for Tomcat: 
-Djndi.name=java:comp/env/jdbc/openchpl
> OCD-988 Caching fixes

- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/surveillance/SurveillanceValidator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
* Show errors when user does not have permission on CHPL product
* validate that total sites is not 0
> OCD-1004: fixed to surveillance bulk upload

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/SurveillanceDAOImpl.java
I believe this is a fix for the error Ashwini is getting on dev. If you guys approve it, can @andlar please push to dev for her? I'll be driving and/or at the dentist's office. Thank you!
> OCD-1004: add null checks to DAO methods in case of bad data

- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/surveillance/SurveillanceValidator.java
Going to merge this since it's blocking Ashwini. Already hot-coded it and tried it on dev since I couldn't re-create locally.
> OCD-1004: add one more null check for empty requirement type

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/SurveillanceDAOImpl.java
* was not setting certification criteria id to null
> OCD-1003: fix surveillance requirement edit

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/CertifiedProductSearchResultDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/DeveloperDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/CertifiedProductDetailsEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SearchViewController.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/web/controller/SearchViewControllerTest.java
Still need to pin down the cause to Andrew's 500 response for decertifications/developers before this can get merged.
> OCD-1016: Fixed access denied by using DAO instead of manager

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/DeveloperManagerImpl.java
ONC wants suspicious activity emails sent when developer status changes
> OCD-1034: actually do send emails on developer status changes

- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/surveillance/SurveillanceValidator.java
add criterion check for surveilled requirements based on answer from jennifer on friday
> OCD-1011: add validation for reqs - has to be in criteria for product

- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/presenter/SurveillanceReportCsvPresenter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/CertifiedProductDetailsDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/CertifiedProductManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
had the certification status date and date of last certification status change mixed up in a few places
> OCD-1088:fix some issues found with certification status change

- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
> OCD-1088: got parameters mixed up for surveillance download

- chpl/chpl-service/src/main/java/gov/healthit/chpl/upload/certifiedProduct/CertifiedProductHandler2014.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/upload/certifiedProduct/CertifiedProductHandler2015.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/AmbulatoryModular2014Validator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProduct2014Validator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProduct2015Validator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductValidatorImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/InpatientModular2014Validator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/web/controller/CertifiedProductControllerTest.java
Still working on the unit test for this (it's not easy to unit test), but I want to get this out to Ashwini to finish up her testing.
> OCD-1096: fixed comparison for boolean value

- RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/surveillance/SurveillanceValidator.java
There are a bunch of whitespace tweaks because I can't bear seeing the "bad" color in Emacs, but there were some actual changes to code in the Validator
> OCD-1253: Restrict surveillance edit when no close date but all closed NCs

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/DeveloperDAOImpl.java
Fixes issue dan found with certain /details calls failing
> OCD-1337: add statusevent fetch to developer dao calls

- RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/surveillance/presenter/SurveillanceOversightAllBrokenRulesCsvPresenter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/surveillance/presenter/SurveillanceReportCsvPresenter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/SurveillanceNonconformityStatus.java
* add Nonconformity Status as a column in the report
* only include nonconformities with a status of Open
> OCD-1379: update surveillance broken rules reports

- RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/SwaggerConfig.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/caching/CacheStatus.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/registration/APIKeyAuthenticationFilter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/StatusController.java
was looking for something i could complete in a shortish amount of time this afternoon to avoid starting something and forgetting about it over the weekend. this seems to work!
> OCD-1394: add /cache_status endpoint and show in Swagger docs

- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductAllowedValidator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductValidator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductValidatorFactoryImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductValidatorImpl.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/ProductManagerTest.java
This should be pushed to staging since it could affect product split.
> OCD-1104: fix bug found by unit tests splitting product with 2011 listings

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/DeveloperManagerImpl.java
The problem was that only ROLE_ADMIN was ever allowed to mark a listing as one of the "trigger" statuses and only ROLE_ADMIN was ever allowed to change the current developer status or the history of developer statuses (changing status of listing to "trigger" status affects both pieces of developer data). Changed checks to allow ROLE_ACB_ADMIN in the one specific scenario listed in the ticket, although the given/when/thens were not totally clear when it comes to user permissions.
> OCD-1438: allow acb admins to change dev status history

- RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/TestFunctionalityDAO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/TestStandardDAO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/TestFunctionalityDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/TestStandardDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/TestStandard.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/TestStandardDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/TestStandardEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/SearchMenuManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertificationResultManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SearchMenuManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductValidatorImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SearchViewController.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/TestStandardDAOTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/SearchMenuManagerTest.java
- chpl/chpl-service/src/test/resources/data/testData.xml
* add certification edition to entity, dto, domain
* disallow duplicate test standards per criteria
* add a few unit tests
* update /data/test_standards call to include edition
> OCD-1483: updates to test standards

- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/HttpUtil.java
Also handles responses as UTF-8 which can prevent a bad POST request due to a special character being returned in the GET.
> OCD-1517: add connectTimeout and socketTimeout so job does not get hung up on one call

- RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/SurveillanceOversightReportApp.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/SurveillanceOversightReportDailyApp.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/SurveillanceOversightReportWeeklyApp.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/SurveillanceOversightRule.java
Sorry about all of the changes; I hadn't realized how many whitespace tweaks were in there
> OCD-1577: Added description of surveillance triggers to emails

- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/NotificationDAOTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/NotificationManagerTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/SearchMenuManagerTest.java
- chpl/chpl-service/src/test/resources/data/testData.xml
My local database had gone awry; resetting it allowed my local results to match up with the Jenkins DB.
> OCD-1569: fix assert to acct for ICS; add test data

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/SurveillanceManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/PendingCertifiedProductManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SurveillanceManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
Hopefully fixes issues brought up by Ashwini:
* Able to confirm the same pending surveillance multiple times
* Contact information for the user who already acted on the pending surveillance was wrong.
> OCD-1372: handle pending surv already confirmed. fix contact info.

- RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProduct2015Validator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProductValidatorImpl.java
I elected to hardcode the warning messages rather than put them in the errors file for a more simple removal in 2 weeks. I can change that around if you guys prefer.
> OCD-1881: Do not require 170.315 (b)(8) to have test procs/tools

- chpl/chpl-service/src/main/java/gov/healthit/chpl/job/SurveillanceUploadJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/SurveillanceManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/SurveillanceUploadManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SurveillanceManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SurveillanceUploadManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
The daily csv/xml generation jobs were broken because of some code I put in SurveillanceManagerImpl for the background upload job processing that I didn't realize would affect other things. I want to merge this into staging since it's locked then I will bring it back into dev and push both.
> OCD-1932: re-refactor surv bg job; csv and xml daily files broken

- OCD-2102_RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/search/CertifiedProductSearchDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/CertifiedProductDTO.java
Only going to DEV
Oh, and look at the commit d2d27cd for the actual code fix. "37af582" is only checkstyle changes
> Ocd 2102 - bugfix for surveillance activity search

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerImpl.java
Mostly whitespace changes. Only actual code change is the last part, and should fix the fact that DEV and STG haven't had new downloadable files for a few days. Hopefully will also fix it in PROD before we break it tonight
> Fix downloadable file generation issue

- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/ActivityController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
> Fixed issue with certified_product/{chplProductNumber} endpoint

- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/chartdata/ProductDataCollector.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/CriterionProductStatisticsDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CriterionProductStatistics.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/CriterionProductStatisticsDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/CriterionProductStatisticsEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerAsync.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/StatisticsManagerImpl.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/CriterionProductStatisticsDAOTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/StatisticsManagerTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/web/controller/StatisticsControllerTest.java
- chpl/chpl-service/src/test/resources/META-INF/persistence.xml
- chpl/chpl-service/src/test/resources/data/testData.xml
FYI, the changes in persistence.xml were just adding the CriterionProductEntity and alphabetizing the XML elements
> OCD-2035: Refactor entity; add unit tests

- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/resource/ListingsByEditionResourceCreatorApp.java
> Fixed problem with XML file extension

- PENDING_PENDING_RELEASE_NOTES.md
- chpl/chpl-service/pom.xml
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/TestFunctionalityDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/PracticeType.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/TestFunctionality.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/TestFunctionalityDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/TestFunctionalityEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedProduct2014Validator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/certifiedProduct/CertifiedtProductTestFunctionalityValidator.java
- chpl/chpl-service/src/main/resources/errors.properties
- chpl/chpl-service/src/test/java/gov/heatlhit/chpl/validation/certifiedProduct/CertifiedProductTestFunctionalityValidatorTest.java
> Updated api to validate test functionality

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/PendingCertifiedProductManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/TestingFunctionalityManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductDetailsManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/PendingCertifiedProductManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/TestingFunctionalityManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
Fixes OCD-1503 issue #1
OCD-1503
> Fixed test functionalities not showing up for edit pending CPs

- PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ProductController.java
- chpl/chpl-api/src/test/java/gov/healthit/chpl/web/controller/ProductControllerTest.java
> Fixed duplicate chpl nbr err msg being displayed when editing product

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/summarystatistics/SummaryStatisticsCreatorJob.java
[#OCD-2275]
I'm going to merge this in an hour or two, barring anyone having an issue with it. Need to merge and re-run summary stats generator for QA ASAP
> Fix Job to use correct bean name

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/BrokenSurveillanceRulesEmailJob.java
> Correctly arrange data in csv file

- PENDING_RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/xmlgenerator/CertifiedProductSearchDetailsXmlGenerator.java
> Fix NPE when running the 2015 XML file creation job

- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/authentication/JWTUserConverterImpl.java
- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/authentication/UserAuthenticator.java
- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/dto/UserDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/InvitationManagerImpl.java
> Return correct "full name" in JWT

- chpl/chpl-resources/src/main/resources-dev/jobs.xml
- chpl/chpl-resources/src/main/resources-production/jobs.xml
- chpl/chpl-resources/src/main/resources-staging/jobs.xml
* Update QA email reports to run at 1100 UTC, not 0011 UTC
> Change Summary Statistics generator to run at 0400 UTC

- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/ContactEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/DeveloperManagerImpl.java
* Also cleaned up annotations on contact table
[#OCD-794]
Needs to go to STG before PROD push on Monday
> Update contact instead of creating new one on developer edit

- PENDING_PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertificationIdController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/certificationId/Validator2014.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/certificationId/Validator20142015.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/certificationId/Validator2015.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/cmsid/CertificationIdTest.java
No website changes needed for this one.
> Ocd-1595 - 2014/2015 cms id info messages

- PENDING_RELEASE_NOTES.md
> Fix PENDING release note indentation

- PENDING_PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CollectionsController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/ApiKeyDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/search/CertifiedProductSearchDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/search/CertifiedProductFlatSearchResult.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/search/CertifiedProductSearchResult.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/ApiKeyDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/search/CertifiedProductBasicSearchResultEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/ApiKeyManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertifiedProductSearchManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/InheritanceErrorsReportEmailJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/RequiredDataReviewer.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/ApiKeyManagerTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/reviewer/RequiredDataReviewerTest.java
> Add Developer Status to search results view

- PENDING_RELEASE_NOTES.md
- chpl/chpl-resources/src/main/resources/errors.properties
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/TestFunctionalityReviewer.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/edition2015/RequiredData2015Reviewer.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/pendingListing/reviewer/PendingListingTestFunctionalityReviewerTest.java
The rest of the code for this ticket is already on staging, so my plan is to first merge it into staging then merge back down into dev and push both.
> Ocd 2449 Change invalid test functionality message from error to warning

- chpl/chpl-service/cleanupXml.sh
> Update script to use folder as parameter

- chpl/chpl-service/src/main/java/gov/healthit/chpl/app/TriggerJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/SurveillanceDownloadableResourceCreatorJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/presenter/SurveillanceCsvPresenter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/presenter/SurveillanceReportCsvPresenter.java
> Correctly format UTC dates on surveillance files

- chpl/chpl-service/cleanupXml.sh
> Display before/after of XML files during deletion

- chpl/chpl-auth/src/main/java/gov/healthit/chpl/auth/jwt/JSONWebKeyRsaJoseJImpl.java
[#codecleanup]
The real changes are in the first commit. All of the resources in this project already had closes on them, so I just added that try-with-resources thing them.
> add try clause to autocloseble resources in auth project

- chpl/chpl-api/src/main/resources/2014 Listing CSV Data Dictionary.csv
- chpl/chpl-api/src/main/resources/2015 Listing CSV Data Dictionary.csv
> OCD-2488 - update data dictionary download files for 2014/2015 download files

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/DownloadableResourceCreatorJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/InterruptJob.java
- chpl/chpl-service/triggerJob.sh
> Add logging to quartz jobs; update script help

- PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
> Update description of the /certified_products endpoint

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
> Properly handle optional data when creating a user

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
> Update "reject" surveillance endpoints

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/TestingLabController.java
> Add new PUT method for ATL undelete

- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/edition2015/TestFunctionality2015Reviewer.java
OCD-2532
Found this bug while looking at ticket OCD-2558.
> Fix issue of 2015 validation using 2014 test functionalities

- PENDING_PENDING_RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/QuestionableActivityDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/questionableActivity/QuestionableActivityDeveloperDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/questionableActivity/QuestionableActivityDeveloperEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/QuestionableActivityManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/questionableactivity/DeveloperQuestionableActivityProvider.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/QuestionableActivityEmailJob.java
> Add Reason to Questionable Activity when changing Developer status

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/TestFunctionalityDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2015/TestFunctionality2015Reviewer.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/reviewer/ListingTestFunctionalityReviewerTest.java
> Fix LazyInitializationException when using TestFunctionalityCriteriaMap

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/TestFunctionalityDAOImpl.java
> Fix QA issue regarding transaction

- chpl/chpl-api/src/main/java/gov/healthit/chpl/SwaggerConfig.java
> Add the /files endpoints to the Swagger documentation

- chpl/chpl-resources/src/main/resources-dev/jobs.xml
- chpl/chpl-resources/src/main/resources-production/jobs.xml
- chpl/chpl-resources/src/main/resources-staging/jobs.xml
- chpl/chpl-service/src/main/resources/jobs.xml
mark mass require password change job as to be deleted after push
[#OCD-2530]
> chore: remove OBE triggers

- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/pendingListing/reviewer/PendingListingTestFunctionalityReviewerTest.java
> Fix broken unit test

- chpl/chpl-resources/src/main/resources-dev/environment.properties
> Add missing swagger env variable to dev environment.properties

- PENDING_PENDING_RELEASE_NOTES.md
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/PendingCertifiedProductDTO.java
> fix: save targeted users on confirm

- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/listing/CertifiedProductSummaryEntity.java
> refactor: remove unused reference to ATLs

- PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
- chpl/chpl-api/src/main/resources/Surveillance (basic) CSV Data Dictionary.csv
- chpl/chpl-resources/src/main/resources-dev/environment.properties
- chpl/chpl-resources/src/main/resources-production/environment.properties
- chpl/chpl-resources/src/main/resources-staging/environment.properties
- chpl/chpl-resources/src/main/resources/environment.properties.template
> feat: add surveillance-basic definition file

- chpl/chpl-api/src/test/java/gov/healthit/chpl/web/controller/SurveillanceControllerTest.java
- chpl/chpl-resources/src/test/resources/data/testData.xml
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/PendingCertifiedProductDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/PendingCertifiedProductDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/PendingCertifiedProductTestingLabDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/listing/pending/PendingCertifiedProductTestingLabMapEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/util/ChplProductNumberUtil.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/ChplNumberReviewer.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/AddressDaoTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/ProductManagerTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/VersionManagerTest.java
I think the remaining one I have locally is due to the security refactor. Have looked at it, but not sure what to do to fix it yet
> Fixing some API tests

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/SurveillanceDAO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/SurveillanceDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/PendingSurveillanceManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/pendingsurveillance/RejectActionPermissions.java
> fix: generate the correct exception when rejecting a deleted pend. surv

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertificationBodyController.java
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/TestingLabController.java
> fix: keep retirement flag set correctly on edit

- .gitignore
- PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertificationBodyController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/CertificationBodyManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/SchedulerManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertificationBodyManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SchedulerManagerImpl.java
> feat: remove ACB from job subscriptions when retired

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SchedulerManagerImpl.java
> fix: fix refatcoring issue with ChplTriggers

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CHPLFileController.java
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ProductController.java
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SchedulerController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CHPLFilesManagerImpl.java
> fix: updated Swagger documentation based on comments and code

- chpl/chpl-service/src/test/java/gov/healthit/chpl/auth/manager/UserManagerTest.java
> fix: unit test related to users

- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/CertifiedProductValidationTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/reviewer/TestToolReviewerTest.java
> fix: fix unit tests related to test tools/ics/retired

- chpl/chpl-resources/src/main/resources/errors.properties
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/TestToolReviewer.java
> Ocd 2652 - Retire test tools

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/AuthenticationController.java
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/dao/impl/UserContactDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/dto/UserDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/JobDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/listener/QuestionableActivityListener.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/CQMCriterionDaoTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/CertificationBodyDaoTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/TestingLabDaoTest.java
> fix: use correct audit ID when impersonating

- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/DecertifiedDeveloperResult.java
Not sure where my code fix went but it was no longer present in our development branch. Maybe it got removed in a merge that was done? Anyway, this just fixes the problem again in the same way.
> fix: re-fix banned developer page npe

- chpl/chpl-resources/src/test/java/gov/healthit/chpl/caching/UnitTestRules.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/PendingCertifiedProductDomainPermissionsTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/pendingcertifiedproduct/GetDetailsByIdActionPermissionsTest.java
I had switched around the permissions code and forgot to update the unit tests.
> OCD-2808 Pending Listing Metadata Test Fixes

- chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/manager/impl/UserManagerImpl.java
I don't think we need to test if the token was created before the current time.  We only need to check if the token is older tan the specified time window.
> Unit test fix

- chpl/chpl-api/src/test/java/gov/healthit/chpl/CHPLTestConfig.java
> test: fix chpl-api unit tests by adding TaskScheduler bean to config

- PENDING_RELEASE_NOTES.md
- chpl/chpl-resources/src/main/resources/quartz.properties
> feat: support clustering of Quartz schedulers

- STAGED_RELEASE_NOTES.md
- chpl/chpl-api/src/test/java/gov/healthit/chpl/listener/CertificationResultTest.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertificationResultManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2014/AmbulatoryG1G2RequiredData2014Reviewer.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2014/InpatientG1G2RequiredData2014Reviewer.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2014/package-info.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/edition2014/AmbulatoryG1G2RequiredData2014Reviewer.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/edition2014/InpatientG1G2RequiredData2014Reviewer.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/pendingListing/reviewer/edition2014/package-info.java
> [#OCD-2895] fix: convert error to warning for g1/g2 validation

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/ProductManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/ProductVersionManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/product/MergeActionPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/productversion/MergeActionPermissions.java
> fix: update permissions for merge of products and versions

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ProductController.java
> fix: update logic for determining if trying to change product owner

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ProductController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/ActionPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/product/UpdateOwnershipActionPermissions.java
> fix: update product ownership history correctly

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ProductController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/ProductOwner.java
> OCD-2821 - Incorrect permissions for edit/split/merge of developer/product/version

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ProductController.java
fix: save product changes when ownership has changed
> OCD-2821: Correct permissions for split/merge/edit

- chpl/chpl-api/src/main/webapp/WEB-INF/web.xml
> fix: update access to /static resources for ff4j console (OCD-2885)

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/FilterDAOImpl.java
> fix: update DAO to handle new user/permission relation (OCD-2755)

- FLAGGED_RELEASE_NOTES.md
- PENDING_RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/filter/JWTAuthenticationFilter.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/FeatureList.java
> Ocd 2820 - Resolve phantom logged in issue

- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/complaint/CreateActionPermissionsTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/complaint/GetAllActionPermissionsTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/complaint/UpdateActionPermissionsTest.java
test: fix tests to use domain objects instead of DTOs
> OCD-2912 - Create a basic complaint

- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/activity/GetUserMaintenanceMetadataActionPermissions.java
fix: update permissions to properly filter user metadata (acbs & cms)
> OCD-2789 - User reports

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/ComplaintManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/complaint/DeleteActionPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/complaint/GetAllActionPermissions.java
> Ocd 2912 - Add basic complaint

- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/ComplaintEntity.java
> feat: update ComplaintEntity to use Util.getNewDate()

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/surveillance/report/AnnualReportDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/surveillance/report/QuarterlyReportDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/surveillance/report/AnnualReportDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/surveillance/report/QuarterlyReportDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/SurveillanceReportManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/surveillance/report/GetAnnualReportActionPermissions.java
> OCD-2917: Annual reports

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/ComplaintDAOImpl.java
> fix: save closed date when a new complaint is created

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ActivityController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/ActivityMetadataManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/activity/GetAnnouncementMetadataActionPermissions.java
> OCD-2754 - Improve Reports responsiveness - Announcements

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/ComplaintDAOImpl.java
fix: fix which ID is used when saving a complaint's surveillances
> OCD-2915 - Associate a complaint with surveillance

- chpl/chpl-service/src/main/java/gov/healthit/chpl/activity/ComplaintActivityMetadataBuilder.java
> qa: Create correct type when retrieving complaint activity

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/AddressDAO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/AddressDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/CertificationBodyDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/DeveloperDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/TestingLabDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/upload/certifiedProduct/CertifiedProductHandler.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/AddressDaoTest.java
> feat: remove address re-use between organizations

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
- chpl/chpl-resources/src/test/resources/META-INF/persistence.xml
- chpl/chpl-service/src/main/java/gov/healthit/chpl/FeatureList.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/UserDeveloperMapDAO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/UserDeveloperMapDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/auth/Authority.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/UserDeveloperMapDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/UserDeveloperMapEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/InvitationManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/UserPermissionsManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/InvitationManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/UserPermissionsManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/ResourcePermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/ActionPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/InvitationDomainPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/UserPermissionsDomainPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/invitation/InviteDeveloperActionPermissions.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/userpermissions/AddDeveloperActionPermissions.java
This is much of a work in progress PR, but does function, and provides the base for a few other tickets
[#OCD-2158]
> flag: support invitation of ROLE_DEVELOPER

- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/InvitationDomainPermissionsTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/UserPermissionsDomainPermissionsTest.java
> test: add new permissions to tests

- RELEASE_NOTES.md
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SurveillanceReportController.java
- chpl/chpl-resources/src/main/resources/errors.properties
- chpl/chpl-service/src/main/java/gov/healthit/chpl/builder/AnnualReportBuilderXlsx.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/builder/SurveillanceSummaryWorksheetBuilder.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/job/ExportAnnualSurveillanceReportJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/job/ExportQuarterlySurveillanceReportJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/summarystatistics/SummaryStatisticsCreatorJob.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/summarystatistics/SummaryStatisticsEmailJob.java
> qa: do not allow annual report create or export without at least one quarterly report

- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/UserPermissionsManagerImplTest.java
> qa: fix unit test failures - missing mock

- chpl/chpl-api/src/test/java/gov/healthit/chpl/CHPLTestConfig.java
- chpl/chpl-api/src/test/java/gov/healthit/chpl/web/controller/SurveillanceReportControllerAnnualReportsTest.java
- chpl/chpl-api/src/test/java/gov/healthit/chpl/web/controller/SurveillanceReportControllerQuarterlyReportsTest.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/QuarterlyReportManagerTest.java
> test: fix annual report tests wrt new requirement of existing quarterly report

- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/CertificationBodyManagerImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/TestingLabManagerImpl.java
> fix: Do not add any users to newly created acb/atl

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/statistics/DeveloperStatisticsDAOImpl.java
> fix: Avoid error in summary statistics when listing is marked deleted.

- chpl/chpl-resources/src/main/resources-dev/jobs.xml
- chpl/chpl-resources/src/main/resources-production/jobs.xml
- chpl/chpl-resources/src/main/resources-staging/jobs.xml
- chpl/chpl-resources/src/main/resources/jobs.xml
> fix: Reschedule nightly quartz jobs to run serially

- chpl/chpl-api/src/test/java/gov/healthit/chpl/CHPLTestConfig.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/surveillance/AddDocumentActionPermissions.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/app/permissions/domain/surveillance/AddDocumentActionPermissionsTest.java
Surveillance edit-NC edit-Supporting document upload not allowed
OCD-2922
> fix: Allow upload of supporting surveillance documentation

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ApiKeyController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/ApiKeyDAO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/ApiKeyDAOImpl.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/ApiKeyManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/impl/ApiKeyManagerImpl.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/ApiKeyManagerTest.java
> feat: Allow retrieval of deleted API keys when retrieving all keys

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/surveillance/report/PrivilegedSurveillanceDAOImpl.java
>  flag: fill in chplProductNumber on create/update of privileged surv

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
> qa: Not allow the last logged in date to be wiped out on edit of user

- chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/impl/ActivityDAOImpl.java
> qa: Fix NPE when creating api key report

- chpl/chpl-resources/src/test/resources/META-INF/persistence.xml
> qa: update entity pkg names for url checker tests

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ChangeRequestController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/changerequest/validation/DeveloperActiveValidation.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/activity/GetActivityDetailsActionPermissions.java
> qa: Fix issues found during testing

- chpl/chpl-service/src/test/java/gov/healthit/chpl/changerequest/validation/DeveloperActiveValidationTest.java
> qa: update broken tests

- chpl/chpl-service/src/test/java/gov/healthit/chpl/dao/impl/MacraMeasureDaoTest.java
- commitlint.config.js
> test: handle newly added macra measures

- chpl/chpl-resources/src/main/resources-production/jobs.xml
> chore: Remove questionable url jobs from prod

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/PendingValidator.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/manager/impl/DeveloperManagerMockitoTest.java
* Fix exception thrown when updating pending listing error/warning counts
* Fix warning count discrepancy of auto-fixed warnings in confirm listings screen due to failed pending listing confirmation
OCD-3104
> fix: Fix error/warning update exception and count discrepancy

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ActivityController.java
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ComplaintController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/FeatureList.java
> flag: remove "complaints" flag, leaving feature enabled

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ActivityController.java
- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SurveillanceReportController.java
- chpl/chpl-api/src/test/java/gov/healthit/chpl/web/controller/SurveillanceReportControllerAnnualReportsTest.java
- chpl/chpl-api/src/test/java/gov/healthit/chpl/web/controller/SurveillanceReportControllerQuarterlyReportsTest.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/FeatureList.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/activity/ActivityMetadataBuilder.java
> flag: remove "surveillance-reporting" flag

- chpl/chpl-resources/src/main/resources-production/jobs.xml
> ci: remove deployed Quartz jobs

- chpl/chpl-api/pom.xml
- chpl/chpl-service/pom.xml
Reverts chpladmin/chpl-api#844
> Revert "Remove duplicate dependencies from poms"

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/summarystatistics/SummaryStatisticsEmailJob.java
> OCD-3143 - fix the switched statistics in the Summary Stats Email

- chpl/chpl-service/src/main/java/gov/healthit/chpl/questionableactivity/ListingQuestionableActivityProvider.java
> OCD-3247 - Fix bug preventing ONC from splitting a developer

- chpl/chpl-service/src/main/java/gov/healthit/chpl/util/Util.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/util/UtilTest.java
> fix!: Allow generation of downloadable files

- chpl/chpl-service/reloadTomcat.sh
> build: use different command to start/stop tomcat

- chpl/chpl-resources/src/main/resources-production/jobs.xml
> ci: remove deployed jobs

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/ActivityController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/FeatureList.java
> [#OCD-3192]: remove enhanced-reports flag

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/urlStatus/QuestionableUrlReportGenerator.java
> OCD_3310 - Questionable URL Report Generator not sending report

- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/MacraMeasure.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/Edition2015ListingValidator.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2015/MacraMeasureComparisonReviewer.java
- chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/reviewer/edition2015/MacraMeasureComparisonReviewerTest.java
> OCD-3341 - ACBs receive error when editing a listing with removed MACRA measures

- .gitignore
- chpl/chpl-resources/src/main/resources-qa/jobs.xml
- chpl/chpl-resources/src/main/resources-qa/log4j2.xml
> [#OCD-3109] BUILD: add files for qa environment

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/urlStatus/QuestionableUrlReportGenerator.java
Show repeated information in columns A - D in questionable URL report
> feat!: Show few repeated information in Questionable URL report

- chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/DeveloperController.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/AddressDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/ContactDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/DeveloperACBMapDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/DeveloperDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/DeveloperStatusDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/DeveloperStatusEventDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/TransparencyAttestationDTO.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/CertificationBodyEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/ComplainantTypeEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/FilterTypeEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/TestFunctionalityEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/TestingLabEntity.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/DeveloperManager.java
- chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/TransparencyAttestationManager.java
> OCD-3345 - Reduce incorrect "activity" in Developer reports

- chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/BrokenSurveillanceRulesCreatorJob.java
> OCD-3350 - Update Quartz jobs to be non-blocking - BrokenSurveillanceRulesCreatorJob
